/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar from the docs folder files (or other category patterns)
 - Make the first item on the list a link
 */

const sidebars = {
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],
};

module.exports = sidebars;
